### ISSUE TITLE
Исправить цикл

### ISSUE THREAD

**Issue by Berupor** [Berupor/Notifications-Service#56]
[Тут](https://github.com/Berupor/Notifications-Service/blob/40c9588b512a056127eb504031496cc7982bb6d6/worker/src/main.py#L47) у Вас выполняется бесконечный цикл, поэтому строчки ниже в принципе не будут достигнуты пока не закончится выполнение main()
import asyncio

async def main():
    while True:
        print('Do some good work ;)')
        await asyncio.sleep(5)
        print("woke up after sleeping |)")

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
    print(" [*] Waiting for messages. To exit press CTRL+C")
    loop.run_forever()
вот что выведет:

➜  tmp python3 main.py
Do some good work ;)
woke up after sleeping |)
Do some good work ;)
woke up after sleeping |)
Do some good work ;)
woke up after sleeping |)
Do some good work ;)
...

**Comment by mburdonos** [comment]
не понял, что надо сделать
просто поменять на loop.close()

**Comment by BigDeepBlue** [comment]
@mburdonos у Вас как только поток выполнения дойдет и выполнит loop.run_until_complete(main())  - начинается бесконечное выполнение main(). А это значит что до loop.run_forever() поток выполнения дойдет только в случае окончания работы loop.run_until_complete(main()) , и по сути скорее всего никогда (разве что при необработанном исключении в main()). Вот потому и сделал этот пример и замечание )
